@csrf
<div class="grid grid-2"><div class="field"><label>Program prioritas / strategis *</label><select name="program_id" required><option value="">Pilih program</option>@foreach($programs as $program)<option value="{{ $program->id }}" @selected(old('program_id', $proposal?->program_id) == $program->id)>{{ $program->name }} ({{ $program->type }})</option>@endforeach</select></div><div class="field"><label>OPD pelaksana *</label><select name="opd_id" required><option value="">Pilih OPD</option>@foreach($opds as $opd)<option value="{{ $opd->id }}" @selected(old('opd_id', $proposal?->opd_id) == $opd->id)>{{ $opd->name }}</option>@endforeach</select></div><div class="field"><label>Tahun anggaran *</label><input type="number" name="budget_year" min="2000" max="2200" value="{{ old('budget_year', $proposal?->budget_year ?? date('Y')) }}" required></div><div class="field"><label>Jenis pekerjaan *</label><select name="work_type" required>@foreach($workTypes as $type)<option @selected(old('work_type', $proposal?->work_type) === $type)>{{ $type }}</option>@endforeach</select></div></div>
<div class="field"><label>Deskripsi pekerjaan</label><textarea name="work_description">{{ old('work_description', $proposal?->work_description) }}</textarea></div><div class="grid grid-2"><div class="field"><label>Lokasi</label><textarea name="location" style="min-height:70px">{{ old('location', $proposal?->location) }}</textarea></div><div class="field"><label>Link titik maps</label><input type="url" name="map_url" value="{{ old('map_url', $proposal?->map_url) }}" placeholder="https://maps.google.com/"></div><div class="field"><label>Anggaran utama</label><input type="number" name="main_budget" min="0" step="0.01" value="{{ old('main_budget', $proposal?->main_budget) }}"></div><div class="field"><div class="field"><label>Tanggal pelaksanaan</label><input type="date" name="execution_date" value="{{ old('execution_date', $proposal?->execution_date?->format('Y-m-d')) }}"></div><div class="field"><label>Status</label><select name="status">@foreach($statuses as $status)<option @selected(old('status', $proposal?->status ?? 'Tercantum Dalam DPA') === $status)>{{ $status }}</option>@endforeach</select></div></div>
<div class="field"><label>Dokumen pendukung dan anggaran</label><div id="supporting-documents">@foreach($supportingDocuments as $index => $document)<div class="grid grid-2 supporting-document-row" style="grid-template-columns:1fr 1fr auto;align-items:end;margin-bottom:10px"><div><label>Nama dokumen</label><input name="supporting_documents[{{ $index }}][name]" value="{{ $document['name'] }}" placeholder="Contoh: FS"></div><div><label>Anggaran pendukung</label><input type="number" name="supporting_documents[{{ $index }}][amount]" value="{{ $document['amount'] }}" min="0" step="0.01" placeholder="20000000"></div><button type="button" class="btn btn-danger remove-supporting-document">Hapus</button></div>@endforeach</div><button type="button" class="btn btn-secondary" id="add-supporting-document">+ Tambah dokumen</button></div><div class="grid grid-2"><div class="field"><label>Persentase progres</label><input type="number" name="progress_percentage" min="0" max="100" value="{{ old('progress_percentage', $proposal?->progress_percentage ?? 0) }}"></div><div class="field"><label>Capaian</label><textarea name="achievement" style="min-height:70px">{{ old('achievement', $proposal?->achievement) }}</textarea></div></div>
<div class="field"><label>Evidence</label><input type="file" name="evidence" accept=".pdf,.jpg,.jpeg,.png"><div class="help">PDF atau gambar, maksimal 5 MB.</div></div><button class="btn btn-primary">Simpan usulan</button> <a class="btn btn-secondary" href="{{ route('proposals.index') }}">Batal</a>
<script>
	const documentContainer = document.getElementById('supporting-documents');
	let documentIndex = {{ count($supportingDocuments) }};
	document.getElementById('add-supporting-document').addEventListener('click', () => {
		documentContainer.insertAdjacentHTML('beforeend', `<div class="grid grid-2 supporting-document-row" style="grid-template-columns:1fr 1fr auto;align-items:end;margin-bottom:10px"><div><label>Nama dokumen</label><input name="supporting_documents[${documentIndex}][name]" placeholder="Contoh: FS"></div><div><label>Anggaran pendukung</label><input type="number" name="supporting_documents[${documentIndex}][amount]" min="0" step="0.01" placeholder="20000000"></div><button type="button" class="btn btn-danger remove-supporting-document">Hapus</button></div>`);
		documentIndex++;
	});
	documentContainer.addEventListener('click', (event) => event.target.closest('.remove-supporting-document')?.closest('.supporting-document-row')?.remove());
</script>
